/* Generated by threadbobber.py from features.yarnproject using ysc 3.2.2. Do not edit. */
#ifndef FEATURES_PROGRAM_H
#define FEATURES_PROGRAM_H
#include "threadbobber.h"
#ifdef __cplusplus
extern "C" {
#endif
extern const ThreadBobberProgram features_program;
#ifdef __cplusplus
}
#endif
enum { FEATURES_VAR_COUNT=22, FEATURES_NODE_COUNT=36, FEATURES_LINE_COUNT=43, FEATURES_COMMAND_COUNT=3 };
#define FEATURES_PROGRAM_HASH 0xc7c44cffu
#define FEATURES_YSC_VERSION "3.2.2"
#if THREADBOBBER_VERSION_MAJOR != 1
#error "This program was generated for ThreadBobber 1.0.0."
#endif
enum { FEATURES_VARIABLE_b=0, FEATURES_VARIABLE_counter=1, FEATURES_VARIABLE_eligible=2, FEATURES_VARIABLE_food=3, FEATURES_VARIABLE_greeting=4, FEATURES_VARIABLE_index=5, FEATURES_VARIABLE_n=6, FEATURES_VARIABLE_name=7, FEATURES_VARIABLE_price=8, FEATURES_VARIABLE_s=9 };
enum { FEATURES_NODE__Yarn_Internal_Cycle_Cycle_First_Condition_0=0, FEATURES_NODE__Yarn_Internal_Cycle_Cycle_Second_Condition_0=1, FEATURES_NODE__Yarn_Internal_NoOffer_NoOffer_Unavailable_Condition_0=2, FEATURES_NODE__Yarn_Internal_Offer_Offer_Ordinary_Condition_0=3, FEATURES_NODE__Yarn_Internal_Offer_Offer_Special_Condition_0=4, FEATURES_NODE__double_price=5, FEATURES_NODE__expensive=6, FEATURES_NODE_CommandExpressions=7, FEATURES_NODE_Cycle=8, FEATURES_NODE_Cycle_First=9, FEATURES_NODE_Cycle_Second=10, FEATURES_NODE_Enums=11, FEATURES_NODE_Expressions=12, FEATURES_NODE_Fairness=13, FEATURES_NODE_Helper=14, FEATURES_NODE_Modulo=15, FEATURES_NODE_NoOffer=16, FEATURES_NODE_NoOffer_Unavailable=17, FEATURES_NODE_Numbers=18, FEATURES_NODE_Offer=19, FEATURES_NODE_Offer_Ordinary=20, FEATURES_NODE_Offer_Special=21, FEATURES_NODE_OptionExpressions=22, FEATURES_NODE_ParityDetour=23, FEATURES_NODE_ParityEnd=24, FEATURES_NODE_ParityStart=25, FEATURES_NODE_Saliency=26, FEATURES_NODE_SmartVariables=27, FEATURES_NODE_StringLoop=28, FEATURES_NODE_StringStress=29, FEATURES_NODE_Strings=30, FEATURES_NODE_Visits=31, FEATURES_NODE_VisitsEnd=32, FEATURES_NODE__ThreadBobber_HasAnyContent_Cycle=33, FEATURES_NODE__ThreadBobber_HasAnyContent_NoOffer=34, FEATURES_NODE__ThreadBobber_HasAnyContent_Offer=35 };
enum { FEATURES_LINE_cycle_first=0, FEATURES_LINE_cycle_second=1, FEATURES_LINE_enums_before=2, FEATURES_LINE_enums_after=3, FEATURES_LINE_expr_result=4, FEATURES_LINE_helper_inside=5, FEATURES_LINE_modulo_even=6, FEATURES_LINE_modulo_signs=7, FEATURES_LINE_unavailable=8, FEATURES_LINE_numbers=9, FEATURES_LINE_ordinary=10, FEATURES_LINE_special=11, FEATURES_LINE_buy=12, FEATURES_LINE_sell=13, FEATURES_LINE_purchased=14, FEATURES_LINE_sold=15, FEATURES_LINE_p_06=16, FEATURES_LINE_p_opt4=17, FEATURES_LINE_p_opt5=18, FEATURES_LINE_p_07=19, FEATURES_LINE_p_08=20, FEATURES_LINE_p_09=21, FEATURES_LINE_p_10=22, FEATURES_LINE_p_11=23, FEATURES_LINE_p_01=24, FEATURES_LINE_p_02=25, FEATURES_LINE_p_opt1=26, FEATURES_LINE_p_opt2=27, FEATURES_LINE_p_opt3=28, FEATURES_LINE_p_03=29, FEATURES_LINE_p_04=30, FEATURES_LINE_p_05=31, FEATURES_LINE_availability=32, FEATURES_LINE_chosen=33, FEATURES_LINE_not_chosen=34, FEATURES_LINE_smart_before=35, FEATURES_LINE_smart_after=36, FEATURES_LINE_string_stress=37, FEATURES_LINE_string_option=38, FEATURES_LINE_string_values=39, FEATURES_LINE_string_after=40, FEATURES_LINE_visits_line=41, FEATURES_LINE_visits_end=42 };
#if THREADBOBBER_CANDIDATES < 8 || THREADBOBBER_MAX_VARS < 22 || THREADBOBBER_OPTIONS < 6 || THREADBOBBER_SUBSTITUTIONS < 4 || THREADBOBBER_COMMAND_ARGS < 4
#error "This program requires a larger ThreadBobber capacity profile."
#endif
#endif
