/* Generated by threadbobber.py from vmtest.yarnproject using ysc 3.2.2. Do not edit. */
#include "vmtest_program.h"
static const char vmtest_strings[]=
"\0"
"salt\0"
"Commands\0"
"Empty\0"
"Expressions\0"
"Loop\0"
"Options\0"
"Recurse\0"
"sync_cmd 7\0"
"Between: commands\0"
"line:between_commands\0"
"pause\0"
"async_cmd \"pause\"\0"
"flag_cmd true\0"
"After: commands {0}\0"
"line:after_commands\0"
"Never\0"
"line:never\0"
"Nope\0"
"line:nope\0"
"wake\0"
"Result: {0} {1} {2}\0"
"line:expr_result\0"
"Prompt: choose\0"
"line:options_prompt\0"
"Always\0"
"line:opt_always\0"
"Sometimes\0"
"line:opt_sometimes\0"
"Rare\0"
"line:opt_rare\0"
"Hosted\0"
"line:opt_hosted\0"
"Picked: always\0"
"line:picked_always\0"
"Picked: sometimes\0"
"line:picked_sometimes\0"
"Picked: rare\0"
"line:picked_rare\0"
"Picked: hosted\0"
"line:picked_hosted\0"
"Done: options\0"
"line:options_done\0"
"$b\0"
"$counter\0"
"$n\0"
"$s\0"
"$Yarn.Internal.Once.line:opt_rare\0";
static const ThreadBobberId vmtest_string_offsets[48]={0,1,6,15,21,33,38,46,54,65,83,105,111,129,143,163,183,189,200,205,215,220,240,257,272,292,299,315,325,344,349,363,370,386,401,420,438,460,473,490,505,524,538,556,559,568,571,574};
static const uint8_t vmtest_code[600]={4,0,0,3,0,0,0,0,4,1,0,4,2,0,8,0,0,0,0,12,0,0,3,1,0,1,0,20,9,0,10,32,0,9,0,5,2,0,20,0,0,1,6,10,29,0,11,2,11,3,3,0,0,0,1,29,0,1,33,0,11,20,8,0,0,64,64,8,0,0,128,64,8,0,0,0,64,12,1,0,8,0,0,0,64,8,0,0,0,64,12,2,0,8,0,0,32,65,8,0,0,128,64,8,0,0,0,64,12,3,0,8,0,0,0,64,12,4,0,14,2,0,11,13,2,0,8,0,0,32,65,8,0,0,0,64,12,5,0,13,3,0,7,20,0,8,0,0,0,64,12,6,0,8,0,0,128,63,12,7,0,8,0,0,0,64,12,8,0,9,0,8,0,0,0,64,12,9,0,14,0,0,11,7,20,0,14,3,0,11,13,2,0,8,0,0,160,64,8,0,0,0,64,12,10,0,8,0,0,16,65,8,0,0,0,64,8,0,0,0,64,12,11,0,8,0,0,0,64,12,1,0,8,0,0,128,191,8,0,0,128,63,8,0,0,0,64,12,12,0,8,0,0,0,64,12,1,0,8,0,0,32,64,8,0,0,128,63,12,13,0,8,0,0,0,64,12,1,0,8,0,0,96,64,8,0,0,128,63,12,13,0,8,0,0,0,64,12,1,0,8,0,0,192,191,8,0,0,128,63,12,14,0,8,0,0,0,64,12,1,0,8,154,153,153,63,8,0,0,128,63,12,15,0,8,0,0,0,64,12,1,0,8,0,0,0,64,8,0,0,128,63,12,16,0,8,0,0,0,64,12,1,0,8,0,0,32,64,8,0,0,128,63,12,17,0,8,0,0,0,64,12,1,0,8,205,204,108,192,8,0,0,128,63,12,18,0,8,0,0,0,64,12,1,0,8,0,0,136,64,8,0,0,128,63,12,19,0,8,0,0,0,64,12,1,0,14,2,0,11,13,2,0,13,0,0,13,3,0,3,4,0,3,0,20,13,1,0,8,0,0,128,63,8,0,0,0,64,12,1,0,14,1,0,11,16,3,0,20,3,5,0,0,0,5,6,0,79,0,0,0,13,2,0,8,0,0,0,64,8,0,0,0,64,12,20,0,5,7,0,88,0,0,1,13,4,0,8,0,0,128,63,12,7,0,5,8,0,97,0,0,1,8,0,0,128,63,8,0,0,128,63,12,21,0,5,9,0,112,0,0,1,6,10,121,0,11,2,11,3,10,0,0,0,1,121,0,11,3,11,0,0,0,1,121,0,11,9,1,14,4,0,11,3,12,0,0,0,1,121,0,11,3,13,0,0,0,1,121,0,3,14,0,0,0,20,18,5,0,20};
static const ThreadBobberNode vmtest_nodes[6]={{2,0,28,THREADBOBBER_NONE,0},{3,28,34,THREADBOBBER_NONE,0},{4,62,383,THREADBOBBER_NONE,0},{5,445,24,THREADBOBBER_NONE,0},{6,469,127,THREADBOBBER_NONE,0},{7,596,4,THREADBOBBER_NONE,0}};
static const ThreadBobberVariable vmtest_vars[5]={{43,2,0x57bc2a83u,0u},{44,1,0x7cd77285u,0u},{45,1,0x63bc3d67u,0u},{46,3,0x46bc0fc0u,1u},{47,2,0xdb409993u,0u}};
static const ThreadBobberLine vmtest_lines[15]={{9,10},{14,15},{16,17},{18,19},{21,22},{23,24},{25,26},{27,28},{29,30},{31,32},{33,34},{35,36},{37,38},{39,40},{41,42}};
static const ThreadBobberCommand vmtest_commands[3]={{0,1,0,0,{{1,1088421888u},{0,0u},{0,0u},{0,0u}},8,0},{1,1,1,0,{{3,11u},{0,0u},{0,0u},{0,0u}},12,0},{2,1,2,0,{{2,1u},{0,0u},{0,0u},{0,0u}},13,0}};
static const ThreadBobberFunction vmtest_funcs[22]={{ThreadBobberFunction_None,0,0,1},{ThreadBobberFunction_NumberAdd,0,2,1},{ThreadBobberFunction_NumberMultiply,0,2,1},{ThreadBobberFunction_NumberDivide,0,2,1},{ThreadBobberFunction_NumberMinus,0,2,1},{ThreadBobberFunction_NumberGreaterThan,0,2,2},{ThreadBobberFunction_StringEqualTo,0,2,2},{ThreadBobberFunction_BoolNot,0,1,2},{ThreadBobberFunction_BoolAnd,0,2,2},{ThreadBobberFunction_BoolOr,0,2,2},{ThreadBobberFunction_NumberModulo,0,2,1},{ThreadBobberFunction_Min,0,2,1},{ThreadBobberFunction_Max,0,2,1},{ThreadBobberFunction_Round,0,1,1},{ThreadBobberFunction_Floor,0,1,1},{ThreadBobberFunction_Ceil,0,1,1},{ThreadBobberFunction_Inc,0,1,1},{ThreadBobberFunction_Dec,0,1,1},{ThreadBobberFunction_Int,0,1,1},{ThreadBobberFunction_Decimal,0,1,1},{ThreadBobberFunction_NumberGreaterThanOrEqualTo,0,2,2},{ThreadBobberFunction_None,1,1,2}};
const ThreadBobberProgram vmtest_program={vmtest_strings,vmtest_string_offsets,48,vmtest_code,600,vmtest_nodes,6,vmtest_vars,5,vmtest_lines,15,vmtest_commands,3,vmtest_funcs,22,0x99d823b4u};
