/* Generated by threadbobber.py from vmtest.yarnproject using ysc 3.2.2. Do not edit. */
#ifndef VMTEST_PROGRAM_H
#define VMTEST_PROGRAM_H
#include "threadbobber.h"
#ifdef __cplusplus
extern "C" {
#endif
extern const ThreadBobberProgram vmtest_program;
#ifdef __cplusplus
}
#endif
enum { VMTEST_VAR_COUNT=5, VMTEST_NODE_COUNT=6, VMTEST_LINE_COUNT=15, VMTEST_COMMAND_COUNT=3 };
#define VMTEST_PROGRAM_HASH 0x99d823b4u
#define VMTEST_YSC_VERSION "3.2.2"
#if THREADBOBBER_VERSION_MAJOR != 1
#error "This program was generated for ThreadBobber 1.0.0."
#endif
enum { VMTEST_VARIABLE_b=0, VMTEST_VARIABLE_counter=1, VMTEST_VARIABLE_n=2, VMTEST_VARIABLE_s=3 };
enum { VMTEST_NODE_Commands=0, VMTEST_NODE_Empty=1, VMTEST_NODE_Expressions=2, VMTEST_NODE_Loop=3, VMTEST_NODE_Options=4, VMTEST_NODE_Recurse=5 };
enum { VMTEST_LINE_between_commands=0, VMTEST_LINE_after_commands=1, VMTEST_LINE_never=2, VMTEST_LINE_nope=3, VMTEST_LINE_expr_result=4, VMTEST_LINE_options_prompt=5, VMTEST_LINE_opt_always=6, VMTEST_LINE_opt_sometimes=7, VMTEST_LINE_opt_rare=8, VMTEST_LINE_opt_hosted=9, VMTEST_LINE_picked_always=10, VMTEST_LINE_picked_sometimes=11, VMTEST_LINE_picked_rare=12, VMTEST_LINE_picked_hosted=13, VMTEST_LINE_options_done=14 };
enum { VMTEST_COMMAND_sync_cmd=0, VMTEST_COMMAND_async_cmd=1, VMTEST_COMMAND_flag_cmd=2, VMTEST_COMMAND_DECLARATION_COUNT=3 };
enum { VMTEST_FUNCTION_host_number=0, VMTEST_FUNCTION_host_flag=1, VMTEST_FUNCTION_COUNT=2 };
#if THREADBOBBER_CANDIDATES < 8 || THREADBOBBER_MAX_VARS < 5 || THREADBOBBER_OPTIONS < 6 || THREADBOBBER_SUBSTITUTIONS < 4 || THREADBOBBER_COMMAND_ARGS < 4
#error "This program requires a larger ThreadBobber capacity profile."
#endif
#endif
